# https://github.com/skupperproject/skupper/blob/master/cmd/site-controller/README.md
apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-password: "rubble"
  console-user: "barney"
  edge: "false"
  ingress: "nodeport"
  ingress-host: cluster2
  router-ingress-host: cluster2
  name: cluster2
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site