apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-password: "rubble"
  console-user: "barney" 
  edge: "true"
  ingress: "nodeport"
  ingress-host: "cluster1"
  name: cluster1
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site