kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
nodes:
- role: control-plane
  # port forward 30070-30072 on the host to 30070-30072 on this node
  extraPortMappings:
  - containerPort: 30070
    hostPort: 30070
  - containerPort: 30071
    hostPort: 30071 
 
