apiVersion: v1
kind: Service
metadata:
  name: cluster2
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: cluster1
spec:
  type: ExternalName
  externalName: host.docker.internal