kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
nodes:
- role: control-plane
  # port forward 30080-30082 on the host to 30080-30082 on this node
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30081
    hostPort: 30081
  - containerPort: 30082
    hostPort: 30082
 
