apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-password: "rubble"
  console-user: "barney"
  console-ingress: "ingress"
  edge: "true"
  ingress: "ingress"
  ingress-host: "cluster1.k8s.local"
  name: cluster1
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site