apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clusternetworker-operator
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: common
  path: ./operator/ClusterNetworker/ClusterNetworker/config/install
  prune: true
