apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: clusternetworker
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: clusternetworker
  template:
    metadata:
      labels:
        operator: clusternetworker
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: webhook-config
        image: operator
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        name: operator
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 5001
          name: https
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /certs
          name: certificates
          readOnly: true
      initContainers:
      - args:
        - webhooks
        - install
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: operator
        name: webhook-installer
        volumeMounts:
        - mountPath: /certs
          name: certificates
        - mountPath: /ca
          name: ca-certificates
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: certificates
      - configMap:
          name: webhook-ca
        name: ca-certificates
