apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpools.demo.ewassef.dev
spec:
  group: demo.ewassef.dev
  names:
    kind: ClusterPool
    listKind: ClusterPoolList
    plural: clusterpools
    singular: clusterpool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - format: int32
      jsonPath: .status.numberOfClusters
      name: Connected Clusters
      priority: 0
      type: integer
    - format: int32
      jsonPath: .status.numberOfExposedServices
      name: Local Exposed Services
      priority: 0
      type: integer
    - format: int32
      jsonPath: .status.overallNumberOfExposedServices
      name: Total Exposed Services
      priority: 0
      type: integer
    - jsonPath: .status.state
      name: State
      priority: 0
      type: string
    - jsonPath: .spec.hasExternalAccess
      name: Has External Access
      priority: 0
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              numberOfClusters:
                format: int32
                type: integer
              numberOfExposedServices:
                format: int32
                type: integer
              overallNumberOfExposedServices:
                format: int32
                type: integer
              state:
                enum:
                - New
                - InstallationInitialized
                - Patching
                - Registered
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              clusterName:
                type: string
              deploymentsExposed:
                items:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                type: array
              exposureType:
                enum:
                - NodePort
                - LoadBalancer
                type: string
              hasExternalAccess:
                type: boolean
              nodeportConfigurations:
                properties:
                  edgeSvc:
                    format: int32
                    type: integer
                  interRouterSvc:
                    format: int32
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
