apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - demo.ewassef.dev
  - coordination.k8s.io
  resources:
  - clusterpools
  - leases
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ''
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - demo.ewassef.dev
  resources:
  - clusterpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
