apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - demo.ewassef.dev
  - ''
  - rbac.authorization.k8s.io
  - coordination.k8s.io
  resources:
  - clusterpools
  - namespaces
  - secrets
  - configmaps
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - pods
  - leases
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - demo.ewassef.dev
  resources:
  - clusterpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
